### PR TITLE
CacheManager.getCacheNames() yields IllegalStateException, if closed

### PR DESCRIPTION
**Pull request by cruftex**
Fixes TCK challenge: https://github.com/jsr107/jsr107tck/issues/87
Consequent change in RI: https://github.com/jsr107/RI/issues/48

### CODE REVIEW

**Comment by christian-esken** [comment]
This should fix https://github.com/jsr107/jsr107tck/issues/87 . I would propose though, to go for the try-catch variant instead of @Test(expected=...). While the latter is more elegant, the try-catch is more exact, as one specific line of code will be checked and not the whole method.

Let me know what you think. If accepted, I will make create a clean single-commit pull request from the change https://github.com/jsr107/jsr107tck/compare/master...trivago:master

**Comment by gregrluck** [comment]
Christian

Nice meeting you the other day. We cannot accept PRs from you unless you sign the Oracle Contributor Agreement. While all of this is Apache 2 licensed, still the copyright owner is Oracle. You can get it here:  http://www.oracle.com/technetwork/community/oca-486395.html.

**Comment by gregrluck** [comment]
Also needed to change CacheManagerManagerTest.

**Comment by christian-esken** [comment]
Greg,
thanks for visiting. It was a pleasure.
I will look into the Oracle Contributor Agreement today. It makes sense as I have collected a couple of other topics (clarification requests, bugs) in https://github.com/trivago/triava/blob/master/tck/README.md and will contribute more.

**Comment by cruftex** [comment]
@christian-esken: Greg wasn't precise. For some PRs the JSPA is needed as well. Just been through this. Statement from Oracle:

> Your OCA has been approved but it only covers contributions to the 
JSR107 Reference Implementation (and any other Oracle sponsored open 
source projects).
> To contribute on the specification and/or the TCK, you also need to sign 
the JSPA as a corporate member.

However, any comments and new findings and more eyes on all these things are highly appreciated!
Just raise issues from your list, for the stuff that you find most important.

Closing the PR, Greg has made the changes already.

**Comment by christian-esken** [comment]
Thanks for dealing with this ticket @cruftex, and also on the hint about JSPA. I could sign the OCA, but ths JSPA is quite complex beast. I will come back to that if I have bigger contributions. Until then I will create some tickets about my findings, as soon as I am confident about their true nature (e.g. real bug vs unclear docs).

**Comment by cruftex** [comment]
@christian-esken: For your info: I'll dedicate next week to JSR107 and plan to crunch as much as I can. I can also pick the issues from your list and open GH issues. 

Just opened https://github.com/jsr107/jsr107spec/issues/357 for further communication on this. Will take a look on it on Monday or Tuesday.

**Pull request closed without merging**
