### PR TITLE
Updated signature test file for 1.0.0 released API

### LINKED ISSUE #118: Signature test datafile sigtest/cache_1.0.0.sig is empty
Signature test datafile sigtest/cache_1.0.0.sig is empty.

### PR DESCRIPTION
**Pull request by vbekiaris**
In this PR:
- jcache_1.0.0.sig is updated using the provided `setup.sh` script against the released `cache-api-1.0.0.jar` artifact.
- added option in `test.sh` to test for backward (instead of mutual) compatibility of 1.1.0-SNAPSHOT against 1.0.0 API

Fixes #118

### CODE REVIEW

**Comment by cruftex** [comment]
+1

Testing against `../../jsr107spec/target/cache-api-1.1.0-SNAPSHOT.jar` is still not perfect. May be we can add it to the pom, so it picks the correct api according to the rest of the TCK setup. Found this:

https://docs.oracle.com/javacomponents/sigtest-3-1/user-guide/a_maven.htm#Z4000c551039922

Wondering whether there is any guide in JCP about this?

**Comment by vbekiaris** [comment]
Thanks for the feedback @cruftex . Integrating the `sigtest` execution in maven would be great, however it seems the maven plugins are not published to any plugin repository. The closest I could find is [this plugin from Netbeans team](http://search.maven.org/#artifactdetails%7Corg.netbeans.tools%7Csigtest-maven-plugin%7C1.0%7Cmaven-plugin) however it seems it is a fork of an earlier version of `sigtest` and cannot parse properly the generated `sigfile`. There is also [this](http://search.maven.org/#artifactdetails%7Cnet.java.sigtest%7Csigtestdev%7C3.0-b12-v20140219%7Cpom) but it also seems to be derived from an old development version of `sigtest`.

---- update ----

I pushed another commit which adds a local maven repository in `sigtest/plugin-repository` from which the required `sigtest` plugin artifacts will be picked by maven. In this commit `sigtest` becomes a maven module of `tck-parent`. When running `mvn test` with profile `sigtest-1.0.0`, it will perform backwards binary compatibility check of current `cache-api-${jcache.version}` against the `jcache_1.0.0.sig` signature file.

Sample output:
```
$ mvn clean test -Psigtest-1.0.0
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building API signature tests 1.1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ sigtest ---
[INFO] Deleting /Users/bekiarisv/workspace/personal/github/jsr107/jsr107tck/sigtest/target
[INFO] 
[INFO] --- maven-enforcer-plugin:1.0:enforce (enforce-maven) @ sigtest ---
[INFO] 
[INFO] --- maven-dependency-plugin:2.8:copy (copy-current-cache-api) @ sigtest ---
[INFO] Configured Artifact: javax.cache:cache-api:1.1.0-SNAPSHOT:jar
[INFO] Copying cache-api-1.1.0-SNAPSHOT.jar to /Users/bekiarisv/workspace/personal/github/jsr107/jsr107tck/sigtest/target/cache-api-current.jar
[INFO] 
[INFO] --- sigtest-plugin:3.1:test (default) @ sigtest ---
[INFO] SignatureTest report
[INFO] Base version: 1.0.0
[INFO] Tested version: 
[INFO] Check mode: src [throws normalized]
[INFO] Constant checking: on
[INFO] 
[INFO] Warning: Not found annotation type javax.enterprise.util.Nonbinding
[INFO] 
Class javax.cache.annotation.CacheAnnotationConfigurationException
[INFO]   warn: "W1.1 - API type added" : CLASS public javax.cache.annotation.CacheAnnotationConfigurationException
[INFO] 
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.614 s
[INFO] Finished at: 2016-12-22T13:23:45+02:00
[INFO] Final Memory: 10M/81M
[INFO] ------------------------------------------------------------------------
```

**Comment by vbekiaris** [comment]
@cruftex what do you think about the additional `sigtest` maven module?

**Comment by cruftex** [comment]
TODO:
- remove sigtest jar from PR
- add a comment that the jar needs to be downloaded and installed separately

**Comment by vbekiaris** [comment]
I reverted the additional maven module described above because I was not able to locate the `sigtest-plugin` artifacts any more on the [sigtest homepage](https://wiki.openjdk.java.net/display/CodeTools/sigtest). This pull request just updates the signature file and the existing `test.sh` script.

**Pull request merged**
